### ISSUE TITLE
Save warnings to .log file

### ISSUE THREAD

**Issue by danheck** [mpt-network/mptcomparison#3]
Given the instability of some methods and the time the computations take, I think it would be a good idea to save warnings and messages to a log file (at least optionally). Two options come to mind:

A)  Using `messages <- capture.output(...)`  Thereby we could store warnings in a second object in the .RData file.
B) Change the `sink("R_messages.log")`  thereby we generate a text file.

Any ideas on that? I prefer option B.

**Comment by singmann** [comment]
I agree, option B sounds good. 

However, I think it would also be important that each method then declares that it starts now and ends now, so that we know which message belongs to which method. 

Also, I think it would be best to have this in the package then as well.

**Comment by danheck** [comment]
I've added this functionally via an option `LOG_FILE=TRUE`, see https://github.com/mpt-network/mptcomparison/commit/f402ed1eb9ab69e09025a9c962843162a18c3bf7
