### ISSUE TITLE
More than 2 between conditions

### ISSUE THREAD

**Issue by danheck** [mpt-network/mptcomparison#6]
`droplevels` throws an error, but I am not sure whether I can remove it without side effects:
https://github.com/mpt-network/mptcomparison/blob/f402ed1eb9ab69e09025a9c962843162a18c3bf7/scripts/mptinr.R#L287

**Comment by singmann** [comment]
should be corrected in 6ebd70556db12886b69454e28374564303bff305.

There were actually two bugs. The one in the `MPTinR` script which prevented any comparison for factors with more than two levels.

In addition, the results table for between subjects comparisons contained superfluous rows (i.e., not only the pairwise comparisons of the factors). Both bugs should be corrected now.
